"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import type { UiLocale } from "@/modules/auth/profile";
import { Button, Dialog, EmptyState, StatusBadge, formatUiDate, translate } from "@/app/components/ui-next";

type Task = { id: string; title: string; state: "todo" | "doing" | "done" | "archived"; assignedTo: string | null; assigneeName: string | null; activityId: string | null; dueAt: Date | string | null; notes: string | null; version: number };
type Activity = { id: string; title: string };
type Assignee = { id: string; displayName: string };

export function TasksView({ projectId, locale, tasks, activities, assignees, canCreate }: { projectId: string; locale: UiLocale; tasks: Task[]; activities: Activity[]; assignees: Assignee[]; canCreate: boolean }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Task | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function call(path: string, init: RequestInit) { const response = await fetch(path, init); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).reason || translate(locale, "error.internal.title")); router.refresh(); }
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); const form = new FormData(event.currentTarget); try { await call(`/api/app/projects/${encodeURIComponent(projectId)}/tasks`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), assigneeId: form.get("assigneeId") || null, activityId: form.get("activityId") || null, dueAt: toIso(form.get("dueAt")), notes: form.get("notes") }) }); setOpen(false); } catch (cause) { setError(cause instanceof Error ? cause.message : translate(locale, "error.internal.title")); } finally { setSaving(false); } }
  async function update(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; setSaving(true); setError(null); const form = new FormData(event.currentTarget); try { await call(`/api/app/projects/${encodeURIComponent(projectId)}/tasks/${encodeURIComponent(editing.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), state: form.get("state"), assigneeId: form.get("assigneeId") || null, dueAt: toIso(form.get("dueAt")), notes: form.get("notes"), expectedVersion: editing.version }) }); const activityId = String(form.get("activityId") || ""); if (activityId !== (editing.activityId || "")) { await call(`/api/app/projects/${encodeURIComponent(projectId)}/tasks/${encodeURIComponent(editing.id)}/activity${activityId ? "" : `?expectedVersion=${editing.version + 1}`}`, activityId ? { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ activityId, expectedVersion: editing.version + 1 }) } : { method: "DELETE" }); } setEditing(null); } catch (cause) { setError(cause instanceof Error ? cause.message : translate(locale, "error.internal.title")); } finally { setSaving(false); } }
  return <section className="ui-next-work-page" aria-labelledby="tasks-title"><header className="ui-next-work-page__header"><div><h2 id="tasks-title">{translate(locale, "tasks.title")}</h2><p>{translate(locale, "tasks.description")}</p></div>{canCreate ? <Button type="button" variant="primary" onClick={() => { setError(null); setOpen(true); }}>{translate(locale, "tasks.new")}</Button> : null}</header>{tasks.length ? <ul className="ui-next-task-list" role="list">{tasks.map((task) => <li key={task.id}><button type="button" className="ui-next-task-list__row" onClick={() => canCreate && setEditing(task)}><span><strong>{task.title}</strong><small>{task.assigneeName || translate(locale, "tasks.unassigned")}{task.dueAt ? ` · ${formatUiDate(task.dueAt, locale)}` : ""}{task.activityId ? ` · ${activities.find((activity) => activity.id === task.activityId)?.title || translate(locale, "tasks.activity")}` : ""}</small></span><StatusBadge tone={task.state === "done" ? "success" : task.state === "doing" ? "information" : "neutral"}>{translate(locale, `tasks.state.${task.state}`)}</StatusBadge></button></li>)}</ul> : <EmptyState title={translate(locale, "tasks.emptyTitle")} description={translate(locale, "tasks.emptyDescription")} action={canCreate ? <Button type="button" variant="primary" onClick={() => setOpen(true)}>{translate(locale, "tasks.createFirst")}</Button> : null} />}
    <TaskDialog open={open} onClose={() => setOpen(false)} locale={locale} title={translate(locale, "tasks.create.title")} activities={activities} assignees={assignees} saving={saving} error={error} submitLabel={translate(locale, "tasks.create.submit")} onSubmit={create} />
    <TaskDialog open={Boolean(editing)} onClose={() => setEditing(null)} locale={locale} title={translate(locale, "tasks.edit.title")} activities={activities} assignees={assignees} task={editing} saving={saving} error={error} submitLabel={translate(locale, "common.save")} onSubmit={update} />
  </section>;
}
function TaskDialog({ open, onClose, locale, title, activities, assignees, task, saving, error, submitLabel, onSubmit }: { open: boolean; onClose: () => void; locale: UiLocale; title: string; activities: Activity[]; assignees: Assignee[]; task?: Task | null; saving: boolean; error: string | null; submitLabel: string; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { return <Dialog open={open} onClose={onClose} title={title} closeLabel={translate(locale, "common.close")}><form className="ui-next-work-form" onSubmit={onSubmit}><label><span>{translate(locale, "tasks.field.title")}</span><input name="title" defaultValue={task?.title || ""} required maxLength={300} autoFocus /></label><label><span>{translate(locale, "tasks.field.assignee")}</span><select name="assigneeId" defaultValue={task?.assignedTo || ""}><option value="">{translate(locale, "tasks.unassigned")}</option>{assignees.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label><label><span>{translate(locale, "tasks.field.activity")}</span><select name="activityId" defaultValue={task?.activityId || ""}><option value="">{translate(locale, "tasks.noActivity")}</option>{activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.title}</option>)}</select></label><label><span>{translate(locale, "tasks.field.dueAt")}</span><input name="dueAt" type="datetime-local" defaultValue={toLocalDateTime(task?.dueAt)} /></label>{task ? <label><span>{translate(locale, "tasks.field.state")}</span><select name="state" defaultValue={task.state}>{(["todo", "doing", "done", "archived"] as const).map((state) => <option key={state} value={state}>{translate(locale, `tasks.state.${state}`)}</option>)}</select></label> : null}<label><span>{translate(locale, "tasks.field.notes")}</span><textarea name="notes" rows={3} defaultValue={task?.notes || ""} /></label>{error ? <p className="ui-next-work-form__error" role="alert">{error}</p> : null}<div className="ui-next-work-form__actions"><Button type="button" variant="secondary" onClick={onClose}>{translate(locale, "common.cancel")}</Button><Button type="submit" variant="primary" loading={saving} loadingLabel={translate(locale, "common.loading")}>{submitLabel}</Button></div></form></Dialog> }
function toIso(value: FormDataEntryValue | null) { return typeof value === "string" && value ? new Date(value).toISOString() : null; }
function toLocalDateTime(value: Date | string | null | undefined) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
